- debug:
    msg: Wait up to 10 minutes for our cluster to initialize and come up before we can deploy kube-dns.

- wait_for:
    port: 443
    host: "{{ hostvars[groups['master_nodes'][0]]['ansible_host'] }}"
    timeout: 600

- name: tempfile
  shell: mktemp
  register: tempfile

- template:
    src: templates/kube_dns.j2
    dest: "{{ tempfile.stdout }}"

# This command will return exit code 1 (error) when kube-dns is not yet deployed
- shell: kubectl --namespace=kube-system get pods -l k8s-app=kube-dns -o jsonpath={.items[0]..metadata.name}
  register: checkkubedns
  ignore_errors: yes

# If kube-dns isn't deployed yet, we need to create it
- name: kubectl create kube-dns
  shell: kubectl create -f "{{ tempfile.stdout }}"
  when: checkkubedns.rc

# If it's already deployed, we need to apply eventual changes
- name: kubectl apply kube-dns
  shell: kubectl apply -f "{{ tempfile.stdout }}"
  when: not checkkubedns.rc
