- wait_for:
    port: 443
    host: "{{ hostvars[groups['master_nodes'][0]]['ansible_host'] }}"
    timeout: 600

- name: tempfile
  shell: mktemp
  register: tempfile

- template:
    src: templates/nginx_ingress.j2
    dest: "{{ tempfile.stdout }}"

- name: kubectl apply nginx-ingress
  shell: kubectl apply -f "{{ tempfile.stdout }}"
