- name: restart kubelet.service
  service:
    name: kubelet
    state: restarted

- name: docker restart haproxy
  shell: "docker restart $( docker ps -f ancestor=haproxy:{{ haproxy_version }} --format '{% raw %}{{.ID}}{% endraw %}' )"
